[tool.poetry]
name = "2020"
version = "0.1.0"
description = "advent of code 2020"
authors = ["kindjacket <kindjacket@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.25.0"
python-dotenv = "^0.15.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
